languages:
  - name: asm
    repo: https://github.com/rush-rs/tree-sitter-asm
    suffixes: [asm]

  - name: c
    repo: https://github.com/tree-sitter/tree-sitter-c
    suffixes: [c, h]

  - name: cpp
    repo: https://github.com/tree-sitter/tree-sitter-cpp
    suffixes: [cpp, hpp]

  - name: c_sharp
    repo: https://github.com/tree-sitter/tree-sitter-c-sharp
    suffixes: [cs]

  - name: java
    repo: https://github.com/tree-sitter/tree-sitter-java
    suffixes: [java]

  - name: javascript
    repo: https://github.com/tree-sitter/tree-sitter-javascript
    suffixes: [js, jsx]

  - name: typescript
    repo: https://github.com/tree-sitter/tree-sitter-typescript
    subdir: typescript
    suffixes: [ts]

  - name: tsx
    repo: https://github.com/tree-sitter/tree-sitter-typescript
    subdir: tsx
    suffixes: [tsx]

  - name: python
    repo: https://github.com/tree-sitter/tree-sitter-python
    suffixes: [py]

  - name: ruby
    repo: https://github.com/tree-sitter/tree-sitter-ruby
    suffixes: [rb]

  - name: go
    repo: https://github.com/tree-sitter/tree-sitter-go
    suffixes: [go]

  - name: php
    repo: https://github.com/tree-sitter/tree-sitter-php
    subdir: php
    suffixes: [php]

  - name: perl
    repo: https://github.com/ganezdragon/tree-sitter-perl
    suffixes: [pl, pm]

  - name: cuda
    repo: https://github.com/theHamsta/tree-sitter-cuda
    suffixes: [cu, cuh]

  - name: html
    repo: https://github.com/tree-sitter/tree-sitter-html
    suffixes: [html]

  - name: pascal
    repo: https://github.com/Isopod/tree-sitter-pascal
    suffixes: [pas, pp]

  - name: powershell
    repo: https://github.com/airbus-cert/tree-sitter-powershell
    suffixes: [ps1]

  - name: bash
    repo: https://github.com/tree-sitter/tree-sitter-bash
    suffixes: [sh, bash]

  - name: rust
    repo: https://github.com/tree-sitter/tree-sitter-rust
    suffixes: [rs]

  - name: swift
    repo: https://github.com/alex-pinkus/tree-sitter-swift
    suffixes: [swift]

  - name: css
    repo: https://github.com/tree-sitter/tree-sitter-css
    suffixes: [css]

  - name: vb_dotnet
    repo: https://github.com/CodeAnt-AI/tree-sitter-vb-dotnet
    suffixes: [vb]
